# Generated by Django 3.0.6 on 2020-07-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('savings', models.IntegerField()),
                ('liquid', models.IntegerField()),
            ],
        ),
    ]
