# Generated by Django 3.0.6 on 2020-07-19 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0003_asset_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlystatement',
            unique_together={('user', 'month', 'year')},
        ),
    ]
