# Generated by Django 3.0.6 on 2020-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20200719_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlystatement',
            name='expenses',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlystatement',
            name='liquid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlystatement',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlystatement',
            name='savings',
            field=models.PositiveIntegerField(),
        ),
    ]
