# Generated by Django 3.0.6 on 2020-07-19 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20200719_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlystatement',
            name='month_year',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
    ]
