# Generated by Django 3.0.6 on 2020-07-19 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0006_monthlystatement_month_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlystatement',
            unique_together={('user', 'month_year')},
        ),
    ]
