# Generated by Django 3.0.6 on 2020-07-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20200719_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlystatement',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlystatement',
            name='year',
        ),
    ]
